### ISSUE TITLE
SNAIL

### ISSUE THREAD

**Issue by AnRichard03** [bence056/SNAILL#1]
This is how i wear my shell

**Comment by bence056** [comment]
# Oh no. The Winter Snailider is here.

**Comment by AnRichard03** [comment]
I'm climbing up a garden pail

**Comment by AnRichard03** [comment]
I blame it on my mucus trail, baby!

**Comment by AnRichard03** [comment]
This is how a land snail moves

**Comment by AnRichard03** [comment]
Blame it on my sluggish 'tude

**Comment by AnRichard03** [comment]
Blame it on my mucus trail, baby!

**Comment by AnRichard03** [comment]
Snail!

Snail!
Snail!
Snail!
Snail!

Maybe I'll go eat these leaves

Maybe I'll go climb a tree
Blame it on my mucus tail, baby!

This is how a land snail moves
Blame it on my sluggish 'tude
Blame it on my mucus trail, baby!

Snail!

Snail!
Snail!
Snail!
Snail!


Snail!
Snail!
Snail!
Snail!
Snail!

Snail!

Snail!
Snail!
Snail!
Snail!

Snail!

Snail!
Snail!
