### ISSUE TITLE
Snail thing

### ISSUE THREAD

**Issue by Hgz05** [bence056/SNAILL#2]
After playing the game i think im turning into a snail if you see this im am already lost please send heAAAAAAAAAAAAAA.......

**Comment by bence056** [comment]
Is it only me, or is this SNAIL lookin' kinda THICC...

**Comment by AnRichard03** [comment]
Snail!

This is how I wear my shell

I'm climbing up a garden pail
I blame it on my mucus trail, baby!

This is how a land snail moves
Blame it on my sluggish 'tude
Blame it on my mucus trail, baby!

Snail!

Snail!
Snail!
Snail!
Snail!

Maybe I'll go eat these leaves

Maybe I'll go climb a tree
Blame it on my mucus tail, baby!

This is how a land snail moves
Blame it on my sluggish 'tude
Blame it on my mucus trail, baby!

Snail!

Snail!
Snail!
Snail!
Snail!


Snail!
Snail!
Snail!
Snail!
Snail!

Snail!

Snail!
Snail!
Snail!
Snail!

Snail!

Snail!
Snail!
